server:
  port: 8083
spring:
  application:
    name: dataserver
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.0.98:3306/dataserver?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: Yz2019
    hikari:
      maximum-pool-size: 10000
      minimum-idle: 100
      connection-timeout: 30000
      idle-timeout: 30000
      connection-test-query: SELECT 1

  main:
    allow-bean-definition-overriding: true

  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html

  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/,classpath:/templates/

eureka:
  client:
    ip: 127.0.0.1
    port: 8761
    serviceUrl:
      defaultZone: http://${eureka.client.ip}:${eureka.client.port}/eureka/
  instance:
    prefer-ip-address: true

mybatis:
  mapper-locations:
    - classpath*:/mapper/*.xml
  type-aliases-package: com.services.data.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.test.mapper : debug
