server:
  port: 8761
  ip: localhost
spring:
  application:
    name: eureka-service
eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 30000
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${server.ip}:${server.port}/eureka/
